config/routes.rb
Myproject::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"
  get "store/show"
  resources :products

  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :line_items, dependent: :destroy
has_many :products

def total_price
  line_items.to_a.sum { |item| item.total_price}
end

def add_product(product_id)
  current_item =line_items.find_by(product_id: product_id)
  if current_item
    current_item.quanity +=1
  else
    current_item = line_items.build(product_id: product_id)
  end
  current_item
end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quanity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gift|jpg|png)\z}i, massage:'must be URL  for GIF, JPG or PNG image.'}
  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'line Items present')
      return false
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:card_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url,
        notice: 'Your cart is currently empty'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern
  def set_cart
    @cart=Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart=Cart.create
    session[:cart_id]=@cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart }
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :image_url, :description, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order('id desc')
  end

  def show
    @product= Product.find(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @cart.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h4>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="page-header">
  <%= link_to carts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @cart, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing cart</h1>
</div>

<%= render 'form' %>

app/views/carts/index.html.erb
<div class="page-header">
  <%= link_to new_cart_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cart
  <% end %>
  <h1>Listing carts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @carts) do |cart| %>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/carts/new.html.erb
<div class="page-header">
  <%= link_to carts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cart</h1>
</div>

<%= render 'form' %>

app/views/carts/show.html.erb
<div class="page-header">
  <h1>Your Cart</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th class="Title">Title</th>
      <th class="Image">Image</th>
      <th class="Quantity">Quantity</th>
      <th class="Description">Description</th>
      <th class="Price">Price</th>
    </tr>
    </thead>
    <tbody>
    <% @cart.line_items.each do |item| %>
    <tr>
        <td align-text="center"><%= item.product.title %></td>
        <td class="Image_tag"><%=item.product.image_url %></td>
        <td class="prduct_quantyty"><%= item.quanity %></td>
        <td class="product_description"><%= item.product.description %></td>


        <td class="item_price"><%= number_to_currency(item.total_price) %></td>

    <% end %>
    </tr>
    <td colspan="4" align ="right">Total</td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tbody>
  </table>
</div>
<%= button_to 'Empty cart', @cart, method: :delete,
              data: { confirm: 'Are you sure?' } ,  :class =>'btn btn-danger'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="Images/1394542704_start-here-ubuntuoriginal.png">
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "EBook Shopping", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>

</body>

</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @line_item.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h4>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :product, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cart, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :cart, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<div class="page-header">
  <%= link_to line_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @line_item, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing line_item</h1>
</div>

<%= render 'form' %>

app/views/line_items/index.html.erb
<div class="page-header">
  <%= link_to new_line_item_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Line item
  <% end %>
  <h1>Listing line_items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Product</th>
            <th>Cart</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @line_items) do |line_item| %>
            <td><%= line_item.product %></td>
            <td><%= line_item.cart %></td>
            <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/line_items/new.html.erb
<div class="page-header">
  <%= link_to line_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New line_item</h1>
</div>

<%= render 'form' %>

app/views/line_items/show.html.erb
<div class="page-header">
  <%= link_to line_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_line_item_path(@line_item), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show line_item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Product:</dt>
  <dd><%= @line_item.product %></dd>

  <dt>Cart:</dt>
  <dd><%= @line_item.cart %></dd>

</dl>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image_url, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :image_url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :description, rows: 6, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <%= link_to products_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @product, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <%= link_to new_product_path, :class => 'btn btn-success' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Product
  <% end %>
  <h1>Listing products</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Image url</th>
            <th>Description</th>
            <th>Price</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @products) do |product| %>
            <td><%= product. title %></td>
            <td class="Product_Image"><%= image_tag(product.image_url)%></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td><%= link_to 'Show', product, :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="page-header">
  <%= link_to products_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="page-header">
  <%= link_to products_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_product_path(@product), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show product</h1>
</div>

<dl class="dl-horizontal">
  <dt> title:</dt>
  <dd><%= @product. title %></dd>

  <dt>Image url:</dt>
  <dd><%= @product.image_url %></dd>

  <dt>Description:</dt>
  <dd><%= @product.description %></dd>

  <dt>Price:</dt>
  <dd><%= @product.price %></dd>

</dl>

app/views/store/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="assets/ruby-on-rails slide.jpg">
      <div class="container">
        <div class="carousel-caption">
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="assets/banner2.jpg">
      <div class="container">
        <div class="carousel-caption">
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="assets/banner1.jpg">
      <div class="container">
        <div class="carousel-caption">
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

  <h1 class="Shoping-cart">Shoping cart</h1>
  <!-- Three columns of text below the carousel -->

  <div class="row">
    <% @products.each do |product| %>
    <div class="col-md-3">
      <span class="Store-img"><%= image_tag(product.image_url) %></span><br><br>
      <h2 class="title">Title: <%= product.title %></h2>
          <p align="justify"><%= (product.description) %></p>
      <div class="new-time">
      <img src="assets/new.gif">
      <%="#{time_ago_in_words(product.created_at)} ago "%>
      </div>

          <h4 class="price">Price:  <%= number_to_currency(product.price) %></h4>

      <li class="Align-Price">
        <span class="Li-Price"><%= link_to 'View detail', store_show_path(product_id: product), :class => 'btn btn-success' %></span>
        <span class="Li-Price"><%= button_to 'Add to Cart', line_items_path(product_id: product), :class => 'btn btn-primary' %></span>

      </li>


    </div><!-- /.col-lg-4 -->
    <% end %>
    </div>


  <!-- START THE FEATURETTES -->
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">
  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2014 by Mr.Yim Sopheak, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

</div><!-- /.container -->

<!-- Bootstrap core JavaScript
 ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/docs.min.js"></script>

</body>
</html>

app/views/store/show.html.erb
<div>
  <div class="col-md-4">
    <span class="Store-show-img"><%= image_tag @product.image_url %></span>
    <legend>
      <p aling="center"><span>Price: </span><%= number_to_currency(@product.price)%></p>

    </legend>
  </div>

  <div class="col-lg-8">
    <div class="row">
      <div class="page-header">
        <%= link_to store_url, :class => 'btn btn-info' do%>
            <span class="glyphicon glyphicon-list-alt"></span>
            Back
        <% end %>
        <h1><b><%= @product.title %></b></h1>

      </div>

      <p align="justify"><%= @product.description %></p>


    </div>
  </div>
</div>